# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/makemore',
                'doc_host': 'https://nasheqlbrm.github.io',
                'git_url': 'https://github.com/nasheqlbrm/makemore',
                'lib_path': 'makemore'},
  'syms': {}}
